### ISSUE TITLE
FiveK dataset

### ISSUE THREAD

**Issue by Oktai15** [proceduralia/pytorch-neural-enhance#2]
@proceduralia could you provide dataset for example in zip archive? it's too long download it directly

**Comment by proceduralia** [comment]
Hi Oktai,
The zip file with the entire dataset can be directly downloaded from the official website https://data.csail.mit.edu/graphics/fivek/.

It is about 50 GB in size. Unfortunately, the link provided by the authors for a download in parts seems to be broken.
The script we provide in the repository is indeed slow, since it's based on web scraping, but it can handle a partial download and be restarted from that point. 

Hope this helps.

**Comment by Oktai15** [comment]
Official archive has problem — I need Lightroom to open images. Your scraping gives resized png directly, it’s what I need :)

**Comment by Oktai15** [comment]
I need around 6 hours to get all images for original version and additionally expert C version. I can provide archive with it later in this issue.

**Comment by Oktai15** [comment]
@proceduralia did you notice that original images don't match with corresponding images on the web site when you try to open them using PIL.Image.open(...)? Image has a lot of yellow tone.

Your code in datasets.py:
```
original_im = Image.open(os.path.join(self. original_path, str(idx)+'.png'))
```

**Comment by proceduralia** [comment]
Hello Oktai15,

we did not have this problem during our experiments, as you can see by looking at the images we inserted in the pdf report. Maybe it's just a problem of the specific visualization function you are using?
